### ISSUE TITLE
结果里没有情感词输出

### ISSUE THREAD

**Issue by duxy-ios** [nlpjoe/CCF-BDCI-Automotive-Field-ASC-2018#5]
跑完结果融合后发现 sentiment_word没有像 要求的那样输出 情感词，请教如何能得到 "太贵了" "不舒服" 这些情感词

**Comment by nlpjoe** [comment]
官方不要求这些词，对分数没影响，所以没有

ducy <notifications@github.com> 于2019年2月27日周三 下午5:46写道：

**Comment by duxy-ios** [comment]
好的，感谢
